# -*- coding: utf-8 -*-
"""Byłem grzeczny ;)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxPktctlhz50K9ayV1uRFaC1ZAKuQrmc
"""

Świetny pomysł! Użycie Streamlit pozwoli na łatwe wyświetlenie tej grafiki Matplotlib w interaktywnej aplikacji webowej.

Musimy przenieść logikę rysowania do funkcji i użyć st.pyplot(fig) zamiast plt.show().

Oto kompletny kod, który możesz zapisać jako plik app.py i uruchomić za pomocą streamlit run app.py:

🚀 Kod Streamlit dla Świętego Mikołaja
Zapisz to jako plik np. streamlit_santa.py:

Python

import streamlit as st
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.patches import Polygon, Circle, Rectangle, Ellipse
import numpy as np

def draw_realistic_santa():
    """
    Rysuje bardziej realistycznego Świętego Mikołaja w Matplotlib
    i zwraca obiekt figury (figure object).
    """
    # Kolory
    DARK_RED = '#AA1D1A'
    RED = '#E62E2A'
    WHITE = '#F0F0F0'
    SKIN = '#F7C6A6'
    SHADE_SKIN = '#DDAA88'
    BLACK = '#000000'
    GOLD = '#FFD700'
    SHADE_RED = '#C92926'

    # Utwórz figurę i oś
    fig, ax = plt.subplots(figsize=(7, 9))

    # Ustawienia osi
    ax.set_xlim(-8, 8)
    ax.set_ylim(-10, 8)
    ax.set_aspect('equal', adjustable='box')
    ax.axis('off')

    # --- 1. Tułów (Ciało) ---
    body_points = [
        (-2.8, -5.5), (2.8, -5.5),  # Dół
        (3.5, -0.5), (3.0, 0.5), # Prawe ramię (zaokrąglenie)
        (-3.0, 0.5), (-3.5, -0.5) # Lewe ramię (zaokrąglenie)
    ]
    ax.add_patch(Polygon(body_points, fc=RED, ec=BLACK, lw=1.5, zorder=1))

    # Cieniowanie płaszcza (lewa strona)
    shade_points = [(-2.8, -5.5), (-2.5, -5.5), (-2.5, 0.0), (-3.0, 0.5), (-3.5, -0.5)]
    ax.add_patch(Polygon(shade_points, fc=SHADE_RED, ec='none', zorder=1.5, alpha=0.8))

    # Czarny pas
    belt = Rectangle((-3.5, -1.8), 7, 1.0, fc=BLACK, ec=BLACK, lw=1.5, zorder=2)
    ax.add_patch(belt)

    # Złota klamra pasa
    buckle = Rectangle((-0.7, -1.6), 1.4, 0.6, fc=GOLD, ec=BLACK, lw=1.5, zorder=3)
    ax.add_patch(buckle)

    # Białe futro na dole kurtki (falisty kształt)
    fur_bottom_points = np.array([
        [-3.5, -5.5], [-2.5, -6.0], [-1.0, -5.7], [0, -6.2],
        [1.0, -5.7], [2.5, -6.0], [3.5, -5.5]
    ])
    ax.add_patch(Polygon(fur_bottom_points, fc=WHITE, ec=BLACK, lw=1.5, zorder=2))


    # --- 2. Ręce i Rękawiczki ---
    # Lewe ramię
    arm_left_poly = Polygon([(-3.5, -0.5), (-3.0, -4.0), (-4.5, -4.5), (-5.0, -0.0)],
                            closed=True, fc=RED, ec=BLACK, lw=1.5, zorder=0)
    ax.add_patch(arm_left_poly)
    # Lewy mankiet (zaokrąglony)
    ax.add_patch(Circle((-4.0, -4.0), 1.2, fc=WHITE, ec=BLACK, lw=1.5, zorder=1))
    # Lewa dłoń (czarna rękawiczka)
    ax.add_patch(Circle((-4.0, -4.0), 0.7, fc=BLACK, ec=BLACK, lw=1.5, zorder=2))

    # Prawe ramię
    arm_right_poly = Polygon([(3.5, -0.5), (3.0, -4.0), (4.5, -4.5), (5.0, -0.0)],
                             closed=True, fc=RED, ec=BLACK, lw=1.5, zorder=0)
    ax.add_patch(arm_right_poly)
    # Prawy mankiet
    ax.add_patch(Circle((4.0, -4.0), 1.2, fc=WHITE, ec=BLACK, lw=1.5, zorder=1))
    # Prawa dłoń
    ax.add_patch(Circle((4.0, -4.0), 0.7, fc=BLACK, ec=BLACK, lw=1.5, zorder=2))


    # --- 3. Głowa i Twarz ---
    # Twarz (lekko owalna)
    face_center = (0, 0)
    face_radius_x = 2.2
    face_radius_y = 2.5
    face = Ellipse(face_center, face_radius_x * 2, face_radius_y * 2,
                   fc=SKIN, ec=BLACK, lw=1.5, zorder=3)
    ax.add_patch(face)

    # Cieniowanie twarzy
    shade = Ellipse((0.2, -0.2), 3.0, 3.5, fc=SHADE_SKIN, ec='none', alpha=0.4, zorder=3.5)
    ax.add_patch(shade)

    # Oczy
    ax.add_patch(Circle((-0.7, 0.8), 0.15, fc=BLACK, zorder=4))
    ax.add_patch(Circle((0.7, 0.8), 0.15, fc=BLACK, zorder=4))

    # Nos (z cieniem)
    ax.add_patch(Circle((0, 0.0), 0.3, fc=RED, ec=BLACK, lw=1.5, zorder=4))
    ax.add_patch(Circle((0.0, 0.0), 0.25, fc=DARK_RED, ec='none', alpha=0.5, zorder=4.5))

    # --- 4. Czapka ---
    # Stożek
    cap_cone = Polygon([(0, 2.5), (-2.8, 4.0), (0, 7.5), (2.8, 4.0)], closed=True, fc=RED, ec=BLACK, lw=1.5, zorder=2)
    ax.add_patch(cap_cone)

    # Biały pompon
    pom_pom = Circle((0.5, 7.0), 0.8, fc=WHITE, ec=BLACK, lw=1.5, zorder=2)
    ax.add_patch(pom_pom)

    # Biały pasek na dole czapki
    cap_band = Rectangle((-3.2, 1.5), 6.4, 1.2, fc=WHITE, ec=BLACK, lw=1.5, zorder=3)
    ax.add_patch(cap_band)

    # --- 5. Brody i Wąsy ---
    # Brody (gęsta chmura)
    beard_shape = [
        Circle((-2.5, -0.8), 1.6, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
        Circle((0, -2.5), 2.5, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
        Circle((2.5, -0.8), 1.6, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
        Circle((-1.5, -3.5), 1.5, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
        Circle((1.5, -3.5), 1.5, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
        Circle((0, -4.5), 1.8, fc=WHITE, ec=BLACK, lw=1.0, zorder=3),
    ]
    for p in beard_shape:
        ax.add_patch(p)

    # Wąsy
    mustache_left_poly = Polygon([(-1.5, 0), (-0.5, 0.5), (0, -0.3), (-1.0, -0.8)], closed=True, fc=WHITE, ec=BLACK, lw=1.5, zorder=4)
    mustache_right_poly = Polygon([(1.5, 0), (0.5, 0.5), (0, -0.3), (1.0, -0.8)], closed=True, fc=WHITE, ec=BLACK, lw=1.5, zorder=4)

    ax.add_patch(mustache_left_poly)
    ax.add_patch(mustache_right_poly)

    # --- 6. Nogi i Buty ---
    leg_left_poly = Polygon([(-2.5, -8.0), (0, -8.0), (0, -5.5), (-2.5, -5.5)], fc=RED, ec=BLACK, lw=1.5, zorder=1)
    ax.add_patch(leg_left_poly)

    leg_right_poly = Polygon([(0, -8.0), (2.5, -8.0), (2.5, -5.5), (0, -5.5)], fc=RED, ec=BLACK, lw=1.5, zorder=1)
    ax.add_patch(leg_right_poly)

    # Buty
    boot_left_poly = Polygon([(-3.0, -9.0), (0.0, -9.0), (-0.5, -8.0), (-2.5, -8.0)], closed=True, fc=BLACK, ec=BLACK, lw=1.5, zorder=2)
    ax.add_patch(boot_left_poly)

    boot_right_poly = Polygon([(3.0, -9.0), (0.0, -9.0), (0.5, -8.0), (2.5, -8.0)], closed=True, fc=BLACK, ec=BLACK, lw=1.5, zorder=2)
    ax.add_patch(boot_right_poly)

    plt.title("Bardziej Realistyczny Święty Mikołaj Matplotlib 🌟")

    # Zwrócenie figury Matplotlib
    return fig

# ---------------- Streamlit App ----------------

def main():
    st.set_page_config(page_title="Streamlit Santa", page_icon="🎅")
    st.title("🎅 Święty Mikołaj stworzony za pomocą Matplotlib w Streamlit")
    st.markdown("To jest ilustracja Mikołaja wygenerowana całkowicie przy użyciu prymitywów geometrycznych biblioteki **Matplotlib**, a następnie wyświetlona jako aplikacja webowa dzięki **Streamlit**.")

    # Wywołanie funkcji rysującej i wyświetlenie wyniku w Streamlit
    santa_fig = draw_realistic_santa()
    st.pyplot(santa_fig)

    st.caption("Użyte kształty: Polygon, Circle, Ellipse i Rectangle.")

if __name__ == "__main__":
    main()